### ISSUE TITLE
What do we build for the experiment?

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/addon-shipping#2]
The current [system addon process](https://wiki.mozilla.org/Firefox/Go_Faster/System_Add-ons/Process) is too big and not strictly defined enough to fully automate it. Reasons: 

* code lives in hg.mozilla.org and/or github
* sightly different guidance/requirements for the size of the system addon
  * flag flips don't require Intent to Ship tracking bugs
  * One off addons live in the GH repo [mozilla/one-ff-system-addons](https://github.com/mozilla/one-off-system-add-ons)
  * larger, more complex ones can have their own repo and a very extensive tracking bug ([example1](https://bugzilla.mozilla.org/show_bug.cgi?id=1308656), [example2](https://bugzilla.mozilla.org/show_bug.cgi?id=1280378), [example3](https://bugzilla.mozilla.org/show_bug.cgi?id=1287966))
* Lots of discussion, approvals and back and forth discussions. We don't want to build a comment systems

Instead I propose we focus on improving a small part: XPI signing. The current process is for somebody from ops with SSH access to take the XPI, sign it on the right box, and attach it to the tracking bug. 

__Proposed state machine:__ (changelog below)

1. Web UI for submitting an XPI
1. Notify verifiers that there's work to do
1. Web UI for secondary approval for signing
1. Background worker submit to autograph for signing (issue #5)
1. Uploader that puts XPI onto ftp.mozilla.org (ref [Bug 1281578](https://bugzilla.mozilla.org/show_bug.cgi?id=1281578))
1. Submitter is notified that XPI is ready

__This is good because:__

* Improve security/bus factor that only people with SSH access to the signing system can sign ([ref](https://bugzilla.mozilla.org/show_bug.cgi?id=1312528#c14))
* Remove need to attach XPI to the tracking bug, a public web URL will suffice
* Gives us experience working with Step Functions, Lambda, etc and lets us know if we can scale up this dev process

__What we're intentionally not doing:__

* The intent/dev/review/qa workflow for a system addon. Bugzilla seems fine.
* Publishing addon to balrog in the test channel: `release-sysaddon`

__changelog__ (most recent first)

* change "Uploader that puts XPI into into a public S3 bucket" to " Uploader that puts XPI onto ftp.mozilla.org"
* change "Web UI for verifying XPI" to "Web UI for secondary approval for signing"
* link to issue #5 for autograph signing
* added the change log

**Comment by glasserc** [comment]
In broad strokes, this sounds good to me.

One remark you made in today's meeting was that there was a loophole in the current process whereby the person signing an XPI doesn't have to be signing the same XPI as the one that got reviewed. Is this point 3, "Web UI for verifying XPI"? What sort of verification are we hoping to offer?

I assume that in point 5, "public S3 bucket" means "publicly readable but only writable by the experiment".

**Comment by glasserc** [comment]
In broad strokes, this sounds good to me.

One remark you made in today's meeting was that there was a loophole in the current process whereby the person signing an XPI doesn't have to be signing the same XPI as the one that got reviewed. Is this point 3, "Web UI for verifying XPI"? What sort of verification are we hoping to offer?

I assume that in point 5, "public S3 bucket" means "publicly readable but only writable by the experiment".

**Comment by leplatrem** [comment]
I also like the scope and intentions! It's well focused and seems to help getting rid of some manual steps 👍.

> Web UI for verifying XPI

That verification remains unclear to me. Does *verify* means *introspect*? Or more something like *reporting* from an integrity/sanity/linting check? Would it be interactive? From the notes I can see that review is out of scope, and on the wiki *verification* applies to QA and *test channel*.

**Comment by mostlygeek** [comment]
re: Web UI for verifying XPI

For security, I think that we should have a manual verification for signing an addon. The submission can be less restrictive but only a small group should be able to actually approve that it should be signed. 

Maybe it should be "Web UI for approving signing of XPI". That seems to be more clear.

> I assume that in point 5, "public S3 bucket" means "publicly readable but only writable by the experiment".

Yes. Public read, private write.

**Comment by mostlygeek** [comment]
@jvehent got any feedback on point 3, about requiring human approval before we submit the XPI to autograph?

**Comment by jvehent** [comment]
The Balrog folks wrote an interesting document on implementing the two-man rule: https://docs.google.com/document/d/1Y9_cr2cJ-olldiDHMXhAaWaDMTakcVZP7GrpSX7xEWI/edit#heading=h.s8uo6bjximbf

In a nutshell, the workflow should be similar to:
1. Authenticated mozillian A uploads addon X and requests a signature
2. Authenticated mozillian B approves the signature on addon X
3. The addon shipping service sends X to autograph, retrieves a signature and puts it into the addon XPI file
4. The signed addon is published

With the following requirements:
* The addon shipping service must make sure that X has not changed between steps 1 and 4 (track a sha256 maybe?).
* From a UI perspective, both mozillians must be able to download the addon to inspect its content locally (it's just a zip file).
* The addon shipping service will have to hold hawk credentials in order to talk to autograph, so it must be treated as a high security service.

**Comment by jvehent** [comment]
Note the addon shipping service will have to hold hawk credentials in order to talk to autograph, so it must be treated as a high security service.

**Comment by mostlygeek** [comment]
> treated as a high security service

Any additional guidance on this? Addon-shipping uses stepfn+lambda. It'll be in the default VPC in prod. 

Lambda are run with IAM roles. So presumably we can keep secrets in SOPS and decrypt/parse them at run time. We won't need to use lambda env variables to store the secrets.

**Comment by mostlygeek** [comment]
I think we are clear on what we want to build now for the initial prototype. Closing this issue.
