### ISSUE TITLE
Integrate with Autograph for signing XPI's

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/addon-shipping#5]
Create a reusable lambda function that can take an XPI and pass it off to the Autograph service to be signed. 

We want to create this as a lambda function so it can be reusable in other state machines. We should consider this to be a "high security" component since it needs to hold Hawk credentials for talking with Autograph. 

__Input:__

* Location of XPI file
* SHA256 of expected XPI file 
* Auth credentials to generate a Hawk token

__Output:__

* Location of signed XPI file
* SHA256 of signed XPI file

__Algorithm:__

1. fetches the XPI file
1. verifies against SHA256 in step fn context
1. generates a manifest for signing
1. sends manifest to Autograph for signing (with Hawk creds)
1. adds signature to new XPI file
1. adds sha256(new xpi) to Step fn context
1. uploads new XPI file to S3

__Any failures should:__

* exit with a non 0 response code
* log a message to stdout of the problem

Ref: https://github.com/mozilla-services/addon-shipping/issues/2#issuecomment-282288010

**Comment by mostlygeek** [comment]
@jvehent can you provide some links/information on: 

1. Hawk authentication for autograph
1. Generating a manifest for signing
1. API references for sending payload for signing

**Comment by jvehent** [comment]
1. hawk is your typical auth header with payload signing. eg. https://github.com/Kinto/kinto-signer/blob/91a865a66ba26d10ffeb2e1de8e56b003d7aa91a/kinto_signer/signer/autograph.py

2. I believe AMO currently uses this lib to generate the addon manifest: https://github.com/rtilder/websigning/blob/master/websigning/sign/xpi.py

3. API ref is going to change, will share when this is merged https://github.com/mozilla-services/autograph/pull/46

**Comment by glasserc** [comment]
Should be addressed by #8.
